// source: element.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Jsml.ProtocolBuffers.Element');
goog.provide('proto.Jsml.ProtocolBuffers.Element.ElementAttribute');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Jsml.ProtocolBuffers.Element = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Jsml.ProtocolBuffers.Element.repeatedFields_, null);
};
goog.inherits(proto.Jsml.ProtocolBuffers.Element, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Jsml.ProtocolBuffers.Element.displayName = 'proto.Jsml.ProtocolBuffers.Element';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Jsml.ProtocolBuffers.Element.ElementAttribute = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Jsml.ProtocolBuffers.Element.ElementAttribute, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Jsml.ProtocolBuffers.Element.ElementAttribute.displayName = 'proto.Jsml.ProtocolBuffers.Element.ElementAttribute';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Jsml.ProtocolBuffers.Element.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Jsml.ProtocolBuffers.Element.prototype.toObject = function(opt_includeInstance) {
  return proto.Jsml.ProtocolBuffers.Element.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Jsml.ProtocolBuffers.Element} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Jsml.ProtocolBuffers.Element.toObject = function(includeInstance, msg) {
  var f, obj = {
    attributesList: jspb.Message.toObjectList(msg.getAttributesList(),
    proto.Jsml.ProtocolBuffers.Element.ElementAttribute.toObject, includeInstance),
    childrenList: jspb.Message.toObjectList(msg.getChildrenList(),
    proto.Jsml.ProtocolBuffers.Element.toObject, includeInstance),
    tag: jspb.Message.getFieldWithDefault(msg, 3, ""),
    text: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Jsml.ProtocolBuffers.Element}
 */
proto.Jsml.ProtocolBuffers.Element.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Jsml.ProtocolBuffers.Element;
  return proto.Jsml.ProtocolBuffers.Element.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Jsml.ProtocolBuffers.Element} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Jsml.ProtocolBuffers.Element}
 */
proto.Jsml.ProtocolBuffers.Element.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Jsml.ProtocolBuffers.Element.ElementAttribute;
      reader.readMessage(value,proto.Jsml.ProtocolBuffers.Element.ElementAttribute.deserializeBinaryFromReader);
      msg.addAttributes(value);
      break;
    case 2:
      var value = new proto.Jsml.ProtocolBuffers.Element;
      reader.readMessage(value,proto.Jsml.ProtocolBuffers.Element.deserializeBinaryFromReader);
      msg.addChildren(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTag(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Jsml.ProtocolBuffers.Element.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Jsml.ProtocolBuffers.Element.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Jsml.ProtocolBuffers.Element} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Jsml.ProtocolBuffers.Element.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAttributesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.Jsml.ProtocolBuffers.Element.ElementAttribute.serializeBinaryToWriter
    );
  }
  f = message.getChildrenList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.Jsml.ProtocolBuffers.Element.serializeBinaryToWriter
    );
  }
  f = message.getTag();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Jsml.ProtocolBuffers.Element.ElementAttribute.prototype.toObject = function(opt_includeInstance) {
  return proto.Jsml.ProtocolBuffers.Element.ElementAttribute.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Jsml.ProtocolBuffers.Element.ElementAttribute} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Jsml.ProtocolBuffers.Element.ElementAttribute.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: jspb.Message.getFieldWithDefault(msg, 1, ""),
    value: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Jsml.ProtocolBuffers.Element.ElementAttribute}
 */
proto.Jsml.ProtocolBuffers.Element.ElementAttribute.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Jsml.ProtocolBuffers.Element.ElementAttribute;
  return proto.Jsml.ProtocolBuffers.Element.ElementAttribute.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Jsml.ProtocolBuffers.Element.ElementAttribute} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Jsml.ProtocolBuffers.Element.ElementAttribute}
 */
proto.Jsml.ProtocolBuffers.Element.ElementAttribute.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Jsml.ProtocolBuffers.Element.ElementAttribute.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Jsml.ProtocolBuffers.Element.ElementAttribute.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Jsml.ProtocolBuffers.Element.ElementAttribute} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Jsml.ProtocolBuffers.Element.ElementAttribute.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string key = 1;
 * @return {string}
 */
proto.Jsml.ProtocolBuffers.Element.ElementAttribute.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Jsml.ProtocolBuffers.Element.ElementAttribute} returns this
 */
proto.Jsml.ProtocolBuffers.Element.ElementAttribute.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.Jsml.ProtocolBuffers.Element.ElementAttribute.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Jsml.ProtocolBuffers.Element.ElementAttribute} returns this
 */
proto.Jsml.ProtocolBuffers.Element.ElementAttribute.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated ElementAttribute attributes = 1;
 * @return {!Array<!proto.Jsml.ProtocolBuffers.Element.ElementAttribute>}
 */
proto.Jsml.ProtocolBuffers.Element.prototype.getAttributesList = function() {
  return /** @type{!Array<!proto.Jsml.ProtocolBuffers.Element.ElementAttribute>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Jsml.ProtocolBuffers.Element.ElementAttribute, 1));
};


/**
 * @param {!Array<!proto.Jsml.ProtocolBuffers.Element.ElementAttribute>} value
 * @return {!proto.Jsml.ProtocolBuffers.Element} returns this
*/
proto.Jsml.ProtocolBuffers.Element.prototype.setAttributesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.Jsml.ProtocolBuffers.Element.ElementAttribute=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Jsml.ProtocolBuffers.Element.ElementAttribute}
 */
proto.Jsml.ProtocolBuffers.Element.prototype.addAttributes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.Jsml.ProtocolBuffers.Element.ElementAttribute, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Jsml.ProtocolBuffers.Element} returns this
 */
proto.Jsml.ProtocolBuffers.Element.prototype.clearAttributesList = function() {
  return this.setAttributesList([]);
};


/**
 * repeated Element children = 2;
 * @return {!Array<!proto.Jsml.ProtocolBuffers.Element>}
 */
proto.Jsml.ProtocolBuffers.Element.prototype.getChildrenList = function() {
  return /** @type{!Array<!proto.Jsml.ProtocolBuffers.Element>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Jsml.ProtocolBuffers.Element, 2));
};


/**
 * @param {!Array<!proto.Jsml.ProtocolBuffers.Element>} value
 * @return {!proto.Jsml.ProtocolBuffers.Element} returns this
*/
proto.Jsml.ProtocolBuffers.Element.prototype.setChildrenList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.Jsml.ProtocolBuffers.Element=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Jsml.ProtocolBuffers.Element}
 */
proto.Jsml.ProtocolBuffers.Element.prototype.addChildren = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.Jsml.ProtocolBuffers.Element, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Jsml.ProtocolBuffers.Element} returns this
 */
proto.Jsml.ProtocolBuffers.Element.prototype.clearChildrenList = function() {
  return this.setChildrenList([]);
};


/**
 * optional string tag = 3;
 * @return {string}
 */
proto.Jsml.ProtocolBuffers.Element.prototype.getTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Jsml.ProtocolBuffers.Element} returns this
 */
proto.Jsml.ProtocolBuffers.Element.prototype.setTag = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string text = 4;
 * @return {string}
 */
proto.Jsml.ProtocolBuffers.Element.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Jsml.ProtocolBuffers.Element} returns this
 */
proto.Jsml.ProtocolBuffers.Element.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


